name: app_karengata
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  google_nav_bar: ^5.0.6
  line_awesome_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/logo/primary_logo.png
  image_dark: assets/logo/primary_logo.png

  android_12:
    image: assets/logo/primary_logo.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/logo/primary_logo.png
    icon_background_color_dark: "#272727"


flutter:
  assets:
    - assets/images/
    - assets/logo/
    - assets/videos/
    - assets/fonts/
  uses-material-design: true
